steps:
- name: gcr.io/cloud-builders/docker
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/android:${_VERSION}'
  - '--tag=gcr.io/$PROJECT_ID/android:latest'
  - '.'

substitutions:
  _VERSION: '1.0'

images: ['gcr.io/$PROJECT_ID/android']