name: Docker Image CI

on:  
  push:
    tags: [v*]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build  --build-arg VERSION=v1.12.13+hotfix.8 --tag ventrata/ventrata-flutter-docker:v1.12.13-hotfix.8
